[package]
name = "web2ws"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.23"
tungstenite = "0.23"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
clap = { version = "4.5", features = ["derive"] }